name: Deploy to ECS (Manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Select image tag (example: build-12)"
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: my-first-cluster-1
  ECS_SERVICE: spring-app-task-new-service
  TASK_FAMILY: spring-app-task-new
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY \
            --query taskDefinition > task.json

      - name: Clean task definition
        run: |
          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task.json > clean-task.json

      - name: Update image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.event.inputs.image_tag }}

          jq --arg IMAGE "$IMAGE_URI" \
          '.containerDefinitions[0].image=$IMAGE' \
          clean-task.json > new-task.json

      - name: Register task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task.json > output.json

      - name: Deploy to ECS
        run: |
          TASK_DEF_ARN=$(cat output.json | jq -r '.taskDefinition.taskDefinitionArn')

          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment