name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Enter image tag (example: build-7)"
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: my-first-cluster-1
  ECS_SERVICE: spring-app-task-new-service
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 2. Login to ECR (optional but safe)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build image URI
      - name: Set image URI
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.event.inputs.image_tag }}
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # 4. Deploy to ECS (NO task definition editing)
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment